SELECT NO, NAME, KIND, PRICE, SALEPRICE, MARGIN, CONTENT, IMAGE, DEL_YN, BEST_YN, REG_DATE FROM PRODUCT;

SELECT NO, NAME, KIND, PRICE, SALEPRICE, MARGIN, CONTENT, IMAGE, DEL_YN, BEST_YN, REG_DATE FROM PRODUCT WHERE kind = 2;

SELECT ID, PWD, NAME, EMAIL, ZIP_NUM, ADDRESS, PHONE, LEAVE_YN, JOIN_DATE FROM MEMBER;

SELECT * FROM MEMBER;

SELECT * FROM cart_view;
SELECT * FROM order_view;

SELECT * FROM PRODUCT;

INSERT INTO CART(PNO, MEMBERID, QUANTITY, RESULT_YN, REG_DATE) VALUES(1, 'ONE', 1, '1', SYSDATE);
insert into cart(pno, MEMBERid, quantity) values(2, 'one', 1);

UPDATE cart SET RESULT_YN = '1' WHERE NO = 1;

DELETE FROM cart WHERE NO = 2;

SELECT 
SELECT NO, PNO, MEMBERID, QUANTITY, RESULT_YN, REG_DATE FROM CART;


SELECT * FROM cart;
INSERT INTO orders(id, ORDER_DATE) VALUES('one', sysdate);

SELECT * FROM orders;
SELECT * FROM order_view;
SELECT * FROM ORDER_DETAIL;
SELECT * FROM product;

INSERT INTO ORDER_DETAIL(ono, pno, QUANTITY, RESULT_YN) VALUES (1, 2, 2, 1);

SELECT max(no) FROM orders;

SELECT * FROM order_view ORDER BY odno;

CREATE OR REPLACE VIEW order_VIEW
(ONO, ODNO, ORDERDATE, MEMBERID, MNAME, ZIP_NUM, ADDRESS, PHONE, PNO, PNAME, QUANTITY, SALEPRICE, RESULT)
AS 
SELECT O.NO, OD.NO, O.ORDER_DATE, M.ID, M.NAME, M.ZIP_NUM, M.ADDRESS, M.PHONE, P.NO, P.NAME, od.QUANTITY, P.SALEPRICE, od.RESULT_YN
FROM ORDERS O LEFT JOIN ORDER_DETAIL OD ON od.ono = o.no
		LEFT JOIN MEMBER M ON M.ID = o.ID
		LEFT JOIN product p ON od.PNO = p.NO;
	
SELECT NO, PNO, MEMBERID, MNAME, PNAME, QUANTITY, PSALEPRICE, REG_DATE FROM CART_VIEW ORDER BY NO;

SELECT * FROM ORDER_VIEW ORDER BY odno;

SELECT ONO, ODNO, ORDERDATE, MEMBERID, MNAME, ZIP_NUM, ADDRESS, PHONE, PNO, PNAME, QUANTITY, SALEPRICE, RESULT FROM ORDER_VIEW WHERE memberid = 'one' AND RESULT LIKE '1' AND ono = 1;

SELECT DISTINCT ono FROM order_VIEW WHERE memberid = 'one' AND RESULT = '1' ORDER BY ono DESC;
SELECT * FROM cart;
SELECT * FROM orders ORDER BY NO;
SELECT * FROM ORDER_DETAIL ORDER BY NO;



SELECT * FROM order_view ORDER BY ono;
create or replace view order_view
(ONO, ODNO, ORDERDATE, MEMBERID, MNAME, ZIP_NUM, ADDRESS, PHONE, PNO, PNAME, QUANTITY, SALEPRICE, RESULT)
as
select o.NO, d.NO, o.ORDER_DATE, o.ID, m.NAME, m.ZIP_NUM, m.ADDRESS, m.PHONE, p.NO, p.NAME, d.QUANTITY, p.SALEPRICE, d.RESULT_YN   
  from orders o JOIN order_detail d ON o.NO = d.ONO JOIN member m ON o.ID =m.ID 
       JOIN product p ON d.PNO = p.NO;


select max(no) from orders;
SELECT ONO, ODNO, ORDERDATE, MEMBERID, MNAME, ZIP_NUM, ADDRESS, PHONE, PNO, PNAME, QUANTITY, SALEPRICE, RESULT FROM ORDER_VIEW WHERE MEMBERID = 'one' AND RESULT LIKE '1' AND Ono = 1;

SELECT * FROM cart;
SELECT * FROM ORDER_detail ORDER BY no;
SELECT * FROM ORDERs;


DELETE ORDERs;
INSERT INTO ORDER_DETAIL(ONO, PNO, QUANTITY, RESULT_YN) VALUES(2, 1, 1, '1');


SELECT NO,SUBJECT,CONTENT,REP,ID,REP_YN,WRITE_DATE FROM qna;